name: Keep Supabase Alive

on:
  schedule:
    # Run at midnight (0 0 * *) on Sunday (0) and Friday(5)
    # - cron: '0 0 * * 0,5'
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Cliente Postgres Nativos de Ráfaga
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Ejecutar Consulta SQL Directa al Motor Postgres (Resetea la Pausa)
        run: |
          # Interrogamos al puerto 5432 con psql directo enviando un query dummy a tus activadas
          PGPASSWORD="${{ secrets.SUPABASE_DB_PASSWORD }}" psql \
          -h "${{ secrets.SUPABASE_DB_HOST }}" \
          -p 5432 \
          -U "postgres" \
          -d "postgres" \
          -c "SELECT id FROM public.maestro_licencias_activadas LIMIT 1;"
